---
- name: Configure Split-DNS
  hosts: all
  become: true
  tasks:

    - name: Copy bind config for split-dns
      copy:
        src: "{{ ansible_hostname }}.named.conf.split"
        dest: /etc/named.conf
        owner: root
        group: named
        mode: 0640
      when: '"dns" in group_names'

    - name: Copy dns.lab.client1 zone config
      copy:
        src: "named.dns.lab.client1"
        dest: "/etc/named/named.dns.lab.client1"
        owner: root
        group: named
        mode: 0660
      when: 'ansible_hostname == "ns01"'

    - name: Restart named service
      systemd:
        name: named
        state: restarted
...
